name: Clang Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cxx'

jobs:
  clang-format:
    name: Clang Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: RafikFarhad/clang-format-github-action@v6
      id: clang-format
      with:
        sources: "src/**/*.h,src/**/*.c"

    - run: echo "Formatted with clang-format version ${{ steps.clang-format.outputs.clang-format-version }}"
